server:
  port: 8080

spring:
  profiles:
    active: dev,server
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${zilweney.datasource.driver-class-name}
      url: jdbc:mysql://${zilweney.datasource.host}:${zilweney.datasource.port}/${zilweney.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${zilweney.datasource.username}
      password: ${zilweney.datasource.password}
  redis:
    host: ${zilweney.redis.host}
    port: ${zilweney.redis.port}
    database: ${zilweney.redis.database}
#    password: ${zilweney.redis.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zilweney.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      zilweney:
        mapper: debug
        service: info
        controller: info

zilweney:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ziwen
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key:  ziwen
    # 设置jwt过期时间
    user-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  alioss:
    access-key-id: ${zilweney.alioss.access-key-id}
    access-key-secret: ${zilweney.alioss.access-key-secret}
    endpoint: ${zilweney.alioss.endpoint}
    bucket-name: ${zilweney.alioss.bucket-name}
